version: '2'
services:
  web:
    build: ./frontend
    ports:
      - 8080:8080
    links:
      - api:localApi
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  api:
    build: ./authapi
    ports:
      - 4001:4001
    links:
      - db:mongodb
    volumes:
      - ./authapi:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mongo
    volumes:
      - ./mongoData:/data/db
