version: '2'
services:
  web:
    build: ./frontend
    ports:
      - 8080:8080
    links:
      - auth-api:localApi
      - travels-api:travelsApi
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  auth-api:
    build: ./authapi
    ports:
      - 4001:4001
    links:
      - dbAuth:mongodb
    volumes:
      - ./authapi:/usr/src/app
      - /usr/src/app/node_modules
  travels-api:
    build: ./travelsdispenser
    ports:
      - 5001:5001
    links:
      - dbTravels:mongodb
    volumes:
      - ./travelsdispenser:/usr/src/app
      - /usr/src/app/node_modules
  dbAuth:
    image: mongo
    volumes:
      - ./mongoDataAuth:/data/db
  dbTravels:
    image: mongo
    volumes:
      - ./mongoDataTravels:/data/db
