version: '2'
services:

# frontend app
  web:
    build: .submodules/frontend
    ports:
      - 8080:8080
    links:
      - auth-api:authapi
      - travels-api:travelsapi
    volumes:
      - ./submodules/frontend:/usr/src/app
      - /usr/src/app/node_modules

# auth api
  auth-api:
    build: ./submodules/authapi
    expose:
      - 4001
    ports:
      - 4001:4001
    links:
      - dbAuth:mongodb
    volumes:
      - ./submodules/authapi:/usr/src/app
      - /usr/src/app/node_modules

# travel api
  travels-api:
    build: ./submodules/travelsdispenser
    expose:
      - 5001
    ports:
      - 5001:5001
    links:
      - auth-api:authapi
      - dbTravels:mongodb
    volumes:
      - ./submodules/travelsdispenser:/usr/src/app
      - /usr/src/app/node_modules

# databases
  dbAuth:
    image: mongo
    volumes:
      - ./data/mongoDataAuth:/data/db
  dbTravels:
    image: mongo
    volumes:
      - ./data/mongoDataTravels:/data/db
